/*
  ESP32 CONNECTION GUIDE
  1. Upload an ESP32 sketch that serves JSON at http://YOUR_ESP32_IP/data.
  2. Change CONFIG.deviceIp to your ESP32 IP address.
  3. Change CONFIG.useRealEsp32 to true.
  4. Keep the ESP32 JSON keys as:
     voltage, current, backupActive, relay, espOnline
     Example: {"voltage":230.4,"current":3.8,"backupActive":false,"relay":"MAIN","espOnline":true}
  5. If your ESP32 uses different key names, edit normalizeEsp32Payload().
*/
const CONFIG={deviceId:"SP-PFMS-01",deviceIp:"192.168.4.21",apiUrl:"http://192.168.4.21/data",useRealEsp32:false,requestTimeoutMs:2500,updateMs:3000,maxPoints:24,thresholds:{voltageMin:190,voltageMax:245,currentMin:.2,currentMax:10}};
const state={monitoringEnabled:true,voltage:231,current:3.7,power:"normal",backupActive:false,relay:"MAIN",espOnline:true,forcedFailure:false,activeOutageId:null,eventCounter:1000,alertCounter:0,readings:[],logs:[],alerts:[],filter:"all",search:"",packetCount:0,lastLatency:0,energyToday:0,lastEnergyAt:Date.now(),stateCounts:{normal:18,failure:0,backup:0,warning:2},outageBuckets:{"00-04":0,"04-08":0,"08-12":0,"12-16":0,"16-20":0,"20-24":0},health:[["ESP32","online","Microcontroller telemetry loop is responding."],["Voltage Sensor","online","AC voltage input is calibrated and stable."],["Current Sensor","online","Load current sampling is inside normal range."],["OLED Display","online","Local status screen is synchronized."],["Relay Module","online","Relay channel is ready for backup switching."],["Wi-Fi Module","online","Station mode is connected to the router."],["Local Storage / SPIFFS","online","Recent event cache is writable."]].map(([name,status,description])=>({name,status,description}))};
const $={},charts={};
document.addEventListener("DOMContentLoaded",()=>{cacheDom();seed();setupCharts();bindEvents();tickClock();renderAll();addAlert("info","Dashboard started","Live ESP32 telemetry link initialized.");setInterval(tickClock,1000);setInterval(refreshData,CONFIG.updateMs)});
function cacheDom(){["clock","deviceId","deviceIp","wifi","ring","heroState","heroText","powerCard","power","powerHint","voltage","voltageHint","current","currentHint","backupCard","backup","backupHint","relay","outages","outageHint","healthScore","healthHint","updated","energyToday","packetCount","latencyText","espPill","indicator","bigState","reason","liveVoltage","liveCurrent","vmeter","imeter","mainSupply","backupSupply","relayMini","sensor","esp","logRows","alertList","alertCount","healthGrid","checked","search","toasts","vband","iband","apiEndpoint","dataMode","menuBtn","monitorToggle"].forEach(id=>$[id]=document.getElementById(id))}
function bindEvents(){document.querySelectorAll("nav a").forEach(a=>a.addEventListener("click",()=>{document.querySelectorAll("nav a").forEach(x=>x.classList.remove("active"));a.classList.add("active");if(window.innerWidth<=980)document.querySelector(".sidebar").classList.remove("open")}));$.menuBtn.addEventListener("click",toggleSidebar);$.monitorToggle.onclick=toggleMonitoring;by("refresh").onclick=refreshData;by("fail").onclick=simulateFailure;by("restore").onclick=simulateRestore;by("toggleBackup").onclick=toggleBackup;["export","tableExport","quickExport"].forEach(id=>by(id).onclick=exportLogsCsv);by("clearAlerts").onclick=clearAlerts;$.search.oninput=e=>{state.search=e.target.value.toLowerCase();renderLogs()};document.querySelectorAll(".filter").forEach(btn=>btn.onclick=()=>{document.querySelectorAll(".filter").forEach(b=>b.classList.remove("active"));btn.classList.add("active");state.filter=btn.dataset.filter;renderLogs()})}
function toggleSidebar(){const sidebar=document.querySelector(".sidebar");if(window.innerWidth<=980){sidebar.classList.toggle("open");return}document.querySelector(".app").classList.toggle("sidebar-collapsed")}
function by(id){return document.getElementById(id)}
function seed(){for(let i=0;i<12;i++){const r=createReading(false);r.time=new Date(Date.now()-(12-i)*CONFIG.updateMs);state.readings.push(r)}state.logs=[{id:"EVT-998",type:"Restore",failureTime:timeAgo(42),restoreTime:timeAgo(38),durationMs:240000,voltage:228,current:3.4,backup:"Yes",remarks:"Main supply restored and backup released."},{id:"EVT-997",type:"Failure",failureTime:timeAgo(42),restoreTime:"--",durationMs:0,voltage:82,current:0,backup:"Yes",remarks:"Undervoltage event detected on Phase-A."}];state.alerts=[makeAlert("success","Power restored","Main supply returned to safe operating range.",timeAgo(38)),makeAlert("warn","Backup switched OFF","Relay returned load from backup to main supply.",timeAgo(37)),makeAlert("info","Device online","ESP32 telemetry link verified.",timeAgo(24))]}
function timeAgo(m){return new Date(Date.now()-m*60000)}
function tickClock(){const n=new Date();$.clock.textContent=n.toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"medium"})}
async function refreshData(){if(!state.monitoringEnabled){renderAll();return}const reading=await getSensorData();applyReading(reading);renderAll()}
async function getSensorData(){
  // CHANGE HERE: keep false for presentation/testing. Set CONFIG.useRealEsp32=true after your ESP32 /data endpoint is ready.
  if(!CONFIG.useRealEsp32){state.packetCount++;state.lastLatency=Math.round(rand(7,28));return createReading(state.forcedFailure)}

  // CHANGE HERE: CONFIG.apiUrl must point to your ESP32, for example "http://192.168.1.55/data".
  const started=performance.now();
  const controller=new AbortController();
  const timeout=setTimeout(()=>controller.abort(),CONFIG.requestTimeoutMs);
  try{
    const response=await fetch(CONFIG.apiUrl,{cache:"no-store",signal:controller.signal});
    if(!response.ok)throw new Error(`HTTP ${response.status}`);
    const payload=await response.json();
    state.lastLatency=Math.round(performance.now()-started);
    state.packetCount++;
    return normalizeEsp32Payload(payload);
  }catch(error){
    markHealth("ESP32","offline");
    addAlert("danger","ESP32 data request failed",`Unable to read ${CONFIG.apiUrl}. Check Wi-Fi, IP address, and /data route.`);
    return{time:new Date(),voltage:0,current:0,espOnline:false};
  }finally{
    clearTimeout(timeout);
  }
}

function normalizeEsp32Payload(payload){
  // CHANGE HERE if your ESP32 sends names like voltageValue, amps, backup, or relayState.
  return{
    time:new Date(),
    voltage:Number(payload.voltage ?? payload.voltageValue ?? payload.v ?? 0),
    current:Number(payload.current ?? payload.currentValue ?? payload.amps ?? 0),
    espOnline:payload.espOnline ?? payload.online ?? true,
    backupActive:Boolean(payload.backupActive ?? payload.backup ?? false),
    relay:String(payload.relay ?? payload.relayStatus ?? "MAIN").toUpperCase()
  };
}
function createReading(force){const offline=Math.random()<.025;let voltage,current;if(force){voltage=rand(0,95);current=rand(0,.12)}else{const fault=Math.random()<.06;voltage=fault?rand(80,175):rand(219,238);current=fault?rand(0,.18):rand(2.5,6.4)}return{time:new Date(),voltage:+voltage.toFixed(1),current:+current.toFixed(2),espOnline:!offline}}
function applyReading(reading){const previous=state.power;state.voltage=reading.voltage;state.current=reading.current;state.espOnline=reading.espOnline;state.power=evaluatePower(reading);updateEnergyEstimate();markHealth("ESP32",state.espOnline?"online":"offline");if(typeof reading.backupActive==="boolean")state.backupActive=reading.backupActive;if(reading.relay)state.relay=reading.relay;if(!state.espOnline)addAlert("danger","Device offline","ESP32 connection missed the latest heartbeat.");if(state.power==="failure"){state.stateCounts.failure++;if(!state.backupActive)setBackup(true,"Automatic backup switched ON after failure detection.");if(previous!=="failure")startOutage(reading)}else{state.stateCounts.normal++;if(previous==="failure"){closeOutage(reading);if(state.backupActive&&!CONFIG.useRealEsp32)setBackup(false,"Backup switched OFF after main supply restoration.")}}if(state.backupActive)state.stateCounts.backup++;state.relay=state.backupActive?"BACKUP":state.relay||"MAIN";state.readings.push(reading);state.readings=state.readings.slice(-CONFIG.maxPoints);localStorage.setItem("singlePhaseDashboard",JSON.stringify({readings:state.readings,logs:state.logs.slice(0,50),alerts:state.alerts.slice(0,30),energyToday:state.energyToday}))}

function updateEnergyEstimate(){const now=Date.now();const elapsedHours=(now-state.lastEnergyAt)/3600000;const watts=Math.max(0,state.voltage*state.current);state.energyToday+=watts*elapsedHours/1000;state.lastEnergyAt=now}
function evaluatePower(r){const t=CONFIG.thresholds;return r.voltage<t.voltageMin||r.voltage>t.voltageMax||r.current<t.currentMin||r.current>t.currentMax||!r.espOnline?"failure":"normal"}
function startOutage(r){const id=`EVT-${++state.eventCounter}`;state.activeOutageId=id;incrementOutageBucket(new Date());state.logs.unshift({id,type:"Failure",failureTime:r.time,restoreTime:"--",durationMs:0,voltage:r.voltage,current:r.current,backup:state.backupActive?"Yes":"No",remarks:"Power failure detected by threshold logic."});addAlert("danger","Power failure detected","Main supply is outside safe voltage or current limits.")}
function closeOutage(r){const log=state.logs.find(x=>x.id===state.activeOutageId);if(log){log.type="Restore";log.restoreTime=r.time;log.durationMs=r.time-new Date(log.failureTime);log.voltage=r.voltage;log.current=r.current;log.remarks="Main supply restored and live readings are safe."}state.activeOutageId=null;addAlert("success","Power restored","Voltage and current returned to the configured safe band.")}
function setBackup(on,msg){state.backupActive=on;state.relay=on?"BACKUP":"MAIN";addAlert(on?"warn":"success",on?"Backup switched ON":"Backup switched OFF",msg)}
function toggleBackup(){setBackup(!state.backupActive,state.backupActive?"Manual operator command released backup supply.":"Manual operator command activated backup supply.");renderAll()}
function toggleMonitoring(){state.monitoringEnabled=!state.monitoringEnabled;if(!state.monitoringEnabled){state.power="paused";state.espOnline=false;markHealth("ESP32","offline");addAlert("warn","Monitoring switched OFF","Dashboard data intake, live readings, charts, and event logging are paused.");}else{state.espOnline=true;markHealth("ESP32","online");state.lastEnergyAt=Date.now();addAlert("success","Monitoring switched ON","Dashboard data intake and live monitoring have resumed.");refreshData();return}renderAll()}
function simulateFailure(){if(!state.monitoringEnabled){showToast({level:"warn",title:"Monitoring is OFF",message:"Switch monitoring ON before simulating a failure."});return}state.forcedFailure=true;applyReading({time:new Date(),voltage:+rand(0,90).toFixed(1),current:+rand(0,.1).toFixed(2),espOnline:true});renderAll()}
function simulateRestore(){if(!state.monitoringEnabled){showToast({level:"warn",title:"Monitoring is OFF",message:"Switch monitoring ON before simulating restore."});return}state.forcedFailure=false;applyReading({time:new Date(),voltage:+rand(224,236).toFixed(1),current:+rand(2.8,5.4).toFixed(2),espOnline:true});renderAll()}
function rand(min,max){return min+Math.random()*(max-min)}
function incrementOutageBucket(date){const hour=date.getHours();const key=Object.keys(state.outageBuckets).find(b=>{const[s,e]=b.split("-").map(Number);return hour>=s&&hour<e});if(key)state.outageBuckets[key]++}
function addAlert(level,title,message){const alert=makeAlert(level,title,message,new Date());state.alerts.unshift(alert);state.alerts=state.alerts.slice(0,40);renderAlerts();showToast(alert)}
function makeAlert(level,title,message,time){return{id:++state.alertCounter,level,title,message,time}}
function clearAlerts(){state.alerts=[];renderAlerts()}
function markHealth(name,status){const item=state.health.find(h=>h.name===name);if(item)item.status=status}
function renderAll(){renderHeader();renderOverview();renderLive();renderLogs();renderAlerts();renderHealth();updateCharts()}
function renderHeader(){$.deviceId.textContent=`Device ID: ${CONFIG.deviceId}`;$.deviceIp.textContent=`IP: ${CONFIG.deviceIp}`;$.wifi.textContent=!state.monitoringEnabled?"Monitoring OFF":state.espOnline?"Wi-Fi Online":"Wi-Fi Offline";$.wifi.className=`pill ${!state.monitoringEnabled||!state.espOnline?"danger":"blue"}`}
function renderOverview(){if(!state.monitoringEnabled){document.body.classList.add("monitoring-off");$.monitorToggle.textContent="Switch On Monitoring";$.monitorToggle.className="success";$.powerCard.classList.add("failure-card");$.power.textContent="OFF";$.powerHint.textContent="Monitoring paused by operator";$.voltage.textContent="--";$.current.textContent="--";$.voltageHint.textContent="Data display disabled";$.currentHint.textContent="Data display disabled";$.backupCard.classList.remove("backup-card");$.backup.textContent="--";$.backupHint.textContent="Backup display paused";$.relay.textContent="--";$.outages.textContent="--";$.outageHint.textContent="Event logging paused";$.healthScore.textContent="--";$.healthHint.textContent="Monitoring switched off";$.updated.textContent="--";$.energyToday.textContent="--";$.packetCount.textContent="--";$.latencyText.textContent="Link paused";$.ring.className="failure";$.heroState.textContent="Monitoring Switched Off";$.heroText.textContent="Live data, charts, and event logs are hidden until monitoring is switched on.";return}document.body.classList.remove("monitoring-off");$.monitorToggle.textContent="Switch Off Monitoring";$.monitorToggle.className="danger";const fail=state.power==="failure",mode=fail?"failure":state.backupActive?"backup":"";const latest=state.readings.at(-1)?.time||new Date(),score=healthScore();$.powerCard.classList.toggle("failure-card",fail);$.power.textContent=fail?"OFF":"ON";$.powerHint.textContent=fail?"Failure state active":"Main supply healthy";$.voltage.textContent=state.voltage.toFixed(1);$.current.textContent=state.current.toFixed(2);$.voltageHint.textContent=vHint();$.currentHint.textContent=iHint();$.backupCard.classList.toggle("backup-card",state.backupActive);$.backup.textContent=state.backupActive?"Active":"Standby";$.backupHint.textContent=state.backupActive?"Load running on backup":"Auto switch enabled";$.relay.textContent=state.relay;$.outages.textContent=outagesToday();$.outageHint.textContent=state.activeOutageId?"One outage is active":"No active outage";$.healthScore.textContent=`${score}%`;$.healthHint.textContent=score>90?"All modules responsive":"Module attention required";$.updated.textContent=formatTime(latest);$.energyToday.textContent=state.energyToday.toFixed(2);$.packetCount.textContent=state.packetCount;$.latencyText.textContent=state.lastLatency?`Link latency ${state.lastLatency} ms`:"Link latency -- ms";$.ring.className=mode;$.heroState.textContent=fail?"Power Failure":state.backupActive?"Backup Supply Active":"Normal Supply";$.heroText.textContent=fail?"Abnormal live reading detected":"Stable voltage and current detected"}
function vHint(){const t=CONFIG.thresholds;if(state.voltage<t.voltageMin)return"Undervoltage detected";if(state.voltage>t.voltageMax)return"Overvoltage detected";return"Within safe threshold"}
function iHint(){const t=CONFIG.thresholds;if(state.current<t.currentMin)return"Current dropped below load range";if(state.current>t.currentMax)return"Overcurrent warning";return"Load is stable"}
function renderLive(){if(!state.monitoringEnabled){$.espPill.textContent="Monitoring Paused";$.espPill.className="pill danger";$.indicator.className="indicator failure";$.bigState.textContent="OFF";$.reason.textContent="The website is not fetching, displaying, charting, or logging live readings.";$.liveVoltage.textContent="--";$.liveCurrent.textContent="--";$.vmeter.value=0;$.imeter.value=0;$.mainSupply.textContent="--";$.backupSupply.textContent="--";$.relayMini.textContent="--";$.sensor.textContent="Paused";$.esp.textContent="Paused";$.vband.textContent=`${CONFIG.thresholds.voltageMin} V - ${CONFIG.thresholds.voltageMax} V`;$.iband.textContent=`${CONFIG.thresholds.currentMin} A - ${CONFIG.thresholds.currentMax} A`;$.apiEndpoint.textContent=CONFIG.apiUrl;$.dataMode.textContent="Monitoring OFF";return}const fail=state.power==="failure",backup=state.backupActive&&!fail;$.espPill.textContent=state.espOnline?"ESP32 Connected":"ESP32 Offline";$.espPill.className=`pill ${state.espOnline?"":"danger"}`;$.indicator.className=`indicator ${fail?"failure":backup?"backup":""}`;$.bigState.textContent=fail?"FAILURE":backup?"BACKUP":"NORMAL";$.reason.textContent=fail?"Voltage or current crossed the configured threshold, so the system entered failure mode.":backup?"Backup supply is active while relay output is isolated from main line.":"Voltage and current are inside the configured safety threshold.";$.liveVoltage.textContent=state.voltage.toFixed(1);$.liveCurrent.textContent=state.current.toFixed(2);$.vmeter.value=state.voltage;$.imeter.value=state.current;$.mainSupply.textContent=fail?"OFF":"ON";$.backupSupply.textContent=state.backupActive?"Active":"Standby";$.relayMini.textContent=state.relay;$.sensor.textContent=fail?"Abnormal":"Normal";$.esp.textContent=state.espOnline?"Online":"Offline";$.vband.textContent=`${CONFIG.thresholds.voltageMin} V - ${CONFIG.thresholds.voltageMax} V`;$.iband.textContent=`${CONFIG.thresholds.currentMin} A - ${CONFIG.thresholds.currentMax} A`;$.apiEndpoint.textContent=CONFIG.apiUrl;$.dataMode.textContent=CONFIG.useRealEsp32?"ESP32 API":"Local telemetry feed"}
function renderLogs(){if(!state.monitoringEnabled){$.logRows.innerHTML=`<tr><td colspan="9">Monitoring is switched off. Event log display and new log generation are paused.</td></tr>`;return}const rows=state.logs.filter(l=>state.filter==="all"||l.type.toLowerCase().includes(state.filter)).filter(l=>`${l.id} ${l.type} ${l.remarks} ${l.backup}`.toLowerCase().includes(state.search)).map(l=>`<tr><td>${l.id}</td><td><span class="tag ${l.type.toLowerCase()}">${l.type}</span></td><td>${formatDateTime(l.failureTime)}</td><td>${formatDateTime(l.restoreTime)}</td><td>${formatDuration(l)}</td><td>${Number(l.voltage).toFixed(1)} V</td><td>${Number(l.current).toFixed(2)} A</td><td>${l.backup}</td><td>${l.remarks}</td></tr>`).join("");$.logRows.innerHTML=rows||`<tr><td colspan="9">No matching logs found.</td></tr>`}
function renderAlerts(){$.alertCount.textContent=state.alerts.length;$.alertList.innerHTML=state.alerts.map(a=>`<article class="alert ${a.level}"><b>${a.title}</b><time>${formatDateTime(a.time)}</time><p>${a.message}</p></article>`).join("")||`<article class="alert"><b>No active alerts</b><p>Recent notifications will appear here.</p></article>`}
function renderHealth(){const now=new Date();$.checked.textContent=`Last checked ${formatTime(now)}`;$.healthGrid.innerHTML=state.health.map(h=>`<article class="health-card"><header><h3>${h.name}</h3><span class="pill ${hClass(h.status)}">${cap(h.status)}</span></header><p>${h.description}</p><small>Last checked ${formatTime(now)}</small></article>`).join("")}
function setupCharts(){if(!window.Chart){document.querySelectorAll("canvas").forEach(c=>{const box=document.createElement("div");box.className="chart-fallback";box.textContent="Chart engine unavailable. Readings, logs, alerts, controls, and CSV export remain active.";c.replaceWith(box)});return}Chart.defaults.color="#8ea0b8";Chart.defaults.borderColor="rgba(255,255,255,.1)";charts.voltage=lineChart("voltageChart","Voltage","#38bdf8","V");charts.current=lineChart("currentChart","Current","#2dd4bf","A");charts.outage=new Chart(by("outageChart"),{type:"bar",data:{labels:Object.keys(state.outageBuckets),datasets:[{label:"Outages",data:Object.values(state.outageBuckets),backgroundColor:"rgba(239,68,68,.65)",borderRadius:6}]},options:chartOptions()});charts.state=new Chart(by("stateChart"),{type:"doughnut",data:{labels:["Normal","Failure","Backup","Warning"],datasets:[{data:Object.values(state.stateCounts),backgroundColor:["#22c55e","#ef4444","#f59e0b","#38bdf8"],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:"bottom"}}}})}
function lineChart(id,label,color,unit){return new Chart(by(id),{type:"line",data:{labels:[],datasets:[{label:`${label} (${unit})`,data:[],borderColor:color,backgroundColor:`${color}22`,fill:true,tension:.35,pointRadius:2}]},options:chartOptions()})}
function chartOptions(){return{responsive:true,maintainAspectRatio:false,animation:{duration:450},plugins:{legend:{labels:{boxWidth:12}}},scales:{x:{grid:{display:false}},y:{beginAtZero:true}}}}
function updateCharts(){if(!charts.voltage)return;if(!state.monitoringEnabled){[charts.voltage,charts.current].forEach(c=>{c.data.labels=[];c.data.datasets[0].data=[];c.update()});charts.outage.data.datasets[0].data=Object.keys(state.outageBuckets).map(()=>0);charts.outage.update();charts.state.data.datasets[0].data=[0,0,0,0];charts.state.update();return}const labels=state.readings.map(r=>formatTime(r.time));updateLine(charts.voltage,labels,state.readings.map(r=>r.voltage));updateLine(charts.current,labels,state.readings.map(r=>r.current));charts.outage.data.datasets[0].data=Object.values(state.outageBuckets);charts.outage.update();charts.state.data.datasets[0].data=Object.values(state.stateCounts);charts.state.update()}
function updateLine(chart,labels,data){chart.data.labels=labels;chart.data.datasets[0].data=data;chart.update()}
function exportLogsCsv(){const header=["Event ID","Type","Failure Time","Restore Time","Duration","Voltage","Current","Backup Activated","Remarks"];const rows=state.logs.map(l=>[l.id,l.type,formatDateTime(l.failureTime),formatDateTime(l.restoreTime),formatDuration(l),`${Number(l.voltage).toFixed(1)} V`,`${Number(l.current).toFixed(2)} A`,l.backup,l.remarks]);const csv=[header,...rows].map(r=>r.map(c=>`"${String(c).replaceAll('"','""')}"`).join(",")).join("\n");const blob=new Blob([csv],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`single-phase-power-logs-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url);addAlert("info","CSV exported","Event log file was generated from current dashboard data.")}
function showToast(a){if(!$.toasts)return;const t=document.createElement("div");t.className=`toast ${a.level}`;t.innerHTML=`<b>${a.title}</b><div>${a.message}</div>`;$.toasts.appendChild(t);setTimeout(()=>t.remove(),4200)}
function outagesToday(){return state.logs.filter(l=>isToday(l.failureTime)).length}
function healthScore(){const points={online:100,warning:65,offline:20};return Math.round(state.health.reduce((sum,h)=>sum+points[h.status],0)/state.health.length)}
function hClass(s){return s==="offline"?"danger":s==="warning"?"warn":""}
function isToday(v){const d=new Date(v),t=new Date();return d.toDateString()===t.toDateString()}
function formatTime(v){return new Date(v).toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit",second:"2-digit"})}
function formatDateTime(v){if(v==="--")return"--";return new Date(v).toLocaleString("en-IN",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit",second:"2-digit"})}
function formatDuration(log){let d=log.durationMs;if(log.id===state.activeOutageId)d=Date.now()-new Date(log.failureTime).getTime();if(!d||d<0)return"--";const s=Math.floor(d/1000),m=Math.floor(s/60);return`${m}m ${s%60}s`}
function cap(v){return v.charAt(0).toUpperCase()+v.slice(1)}
